# Generated by Django 4.2.5 on 2023-10-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='meals',
            field=models.ManyToManyField(blank=True, to='food_counter.meal'),
        ),
        migrations.AlterField(
            model_name='date',
            name='total_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='date',
            name='total_carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='date',
            name='total_fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='date',
            name='total_protein',
            field=models.IntegerField(default=0),
        ),
    ]
