# Generated by Django 4.2.5 on 2023-10-17 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_counter', '0002_alter_date_meals_alter_date_total_calories_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='date',
            unique_together={('user', 'date')},
        ),
    ]
